apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kubernetes-dashboard/ks.yaml
  - wordpress/ks.yaml
  - nextcloud/ks.yaml
  - cloudflared/ks.yaml
  - calibre-web/ks.yaml
  #- lyrion-music-server/ks.yaml
 # - navidrome/ks.yaml
  - renovate/ks.yaml
