apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:9Vvmr4yVfLQnLHYkE+rVdhk1I/NNviuMonAKizq34cU4b82HdBxaT7c5MXJ9SnbygBbHA75oWsCyKdLYFKecwm02AKWwKy8Ywv2Ocmu8BJlC1JM4vQ0abtKvKqhQE/Xo4TQC6Thez/RmP33li/gNT3EQidRtv2uZscPn5Fimo9Do0Lw6de3N0TENx7cGY/kkC69PUBL0ukSDw6Za+rYbRK3+yoEKMOm/F6/EtkT5VUPW1QA+QEWmEL1JrT5J8R3a6WMfZ2WoBf8s4ZMglGwHdvOiqlPeDYV3xHXY2Yk/F73muit/JoRYKADKCJja7Z+PEYP9Ng1c8AWfka13J8DupPS2Hntoln68R+XfOPu8Llu0EI4e95GpUVpEI2Df2ata,iv:+ifSrW3DcuT+nZ0fh2tjHbiBLC5GKed2iblTOKxUIUM=,tag:2t0NHO1NzdHA7e/xOcetbg==,type:str]
    identity.pub: ENC[AES256_GCM,data:RTuMdC3cvhELkGCSjZjJwraow+q+pcvkH25xXg+pHWQ1sLo/jNp2us2ST68yuH16WTbgz08Qo6quT6lQPJ5GdqlFuJ73xCpNeGS374TraYSx4zuat+GZ97GhsgGg0+exlYO81gJeonjNIe1xlHsFqssnDXE1JKWUwiPhdoI1Hy7hj7P1ELU9V2TBY8xkVKcDZ6ERsmUkcyhrtDWOKrcPcFApZ5wsPca0dPUSV4QGnLHGdIeECjDitwaiopuILwqISKWwx22gf4p35dIzFQ==,iv:ZpoeaFpPglXyR5A1m44FzyEpuluAqt2tSD8UZfmzN/8=,tag:QhdbR3oMFH1cBH1fwVWyBg==,type:str]
    known_hosts: ENC[AES256_GCM,data:5pQyFX7XTUbWtxJ6OlXbFDYUnQtZHpaLaEKzluqB0bxEY+bDL8isSIk6vXNIMWSZT7M/Dp1vEbJqLKoF75WLnGNV+VoPEXdsakCHoM/M1hPkGX5/5PAIYAK4uX2BF6YN6veUkHLzAyVVOxFxPWOhdoWuWstd3XREUPaTCZHkNqbMD6znc3+gRZJ9nB4FLN82nWkAvVUrBafT/3RHaJSr1Z0ZgXT/0xb+kDrD,iv:KZ5SMp3XfHciiNKAwF8YD0GYQ/udqWaYxczowlds6DU=,tag:vaci0zIiydwEp2gXaDuw1w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age12t0azzawrmfmvjywjcnv7lgrzt76cj7k4vxmw52wr280jwx2j94qly53me
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0N25laWFCZGY2ZDMzdlVZ
            eUIwK3hYS0l4TG1YZzdJN3plVTEyaGowY1JnCjV0MUtqaXExM3QvSHFCdW9rSjVW
            ajNPZkF0NEVPNDJSbGxtRGhEU2JrSXcKLS0tIFZya1p3SnAvVnoyblRIMFFFWHFK
            Z0Q1MWYvck91ZUl5ZVBFZVRxSVVYdkEKmIsGAutcYUnOGwLRi+ked9GFcEzFkpC0
            75Vz/y+KvqpjPcsRqOXGfs0m3iiIoW2jEaBrkwMaM9TVbBV1KdDUHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-19T10:58:56Z"
    mac: ENC[AES256_GCM,data:yQ02evyG+/8IV0ggtbptLQlWJwakqSy9fMNdkCjfk8gvBD7bG46uHCxT/y/NBYt8+ox6X36UW81vT7xapkGmeCu3MWvI2wJCSeU9MhI7W1YajCLn0t7wSM1zeobsIQ9b9kgebQb+BpCo6h2XvmOGgu/ZQuemwnkMpngEy2f7rlo=,iv:9lA2JWtOgFHSM4/ZWkFlR0HY7ewzAqD773DILd129ns=,tag:j4yJgtFE1wvJ0+wGLwOjXA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
