---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - this-repo.yaml
  - truecharts.yaml
  - bjw-s.yaml
  - cloudnative-pg.yaml
  - home-ops-mirror.yaml
  - jetstack.yaml
  - kustomization.yaml
  - metallb.yaml
  - prometheus-community.yaml
  - spegel.yaml
